name: Deploy Production

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy_website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5
      # - run: npm run build
      - uses: ./
        with:
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          channelId: live
          projectId: action-hosting-deploy-demo
          entryPoint: "./demo"
